server {
    listen 80;
    
    # Корневая папка с билдом
    root /usr/share/nginx/html;
    index index.html;

    # Сжатие gzip (чтобы быстрее грузилось)
    gzip on;
    gzip_types text/plain application/javascript text/css;

    location / {
        # Если файл не найден, отдаем index.html (для React Router)
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики (картинки, JS, CSS)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
